version: '3'
    
services:

  mongo:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  digibank-accounts-svc:
    image: boeboe/digibank-accounts-svc
    env_file:
      - ./microservices/accounts/env.list
    ports:
      - "3400:3400"
    depends_on:
      - mongo

  digibank-authentication-svc:
    image: boeboe/digibank-authentication-svc
    env_file:
      - ./microservices/authentication/env.list
    ports:
      - "3200:3200"
    depends_on:
      - mongo

  digibank-bills-svc:
    image: boeboe/digibank-bills-svc
    env_file:
      - ./microservices/bills/env.list
    ports:
      - "3800:3800"
    depends_on:
      - mongo

  digibank-portal-svc:
    image: boeboe/digibank-portal-svc
    env_file:
      - ./microservices/portal/env.list
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - digibank-accounts-svc
      - digibank-authentication-svc
      - digibank-bills-svc
      - digibank-support-svc
      - digibank-transactions-svc

  digibank-support-svc:
    image: boeboe/digibank-support-svc
    env_file:
      - ./microservices/support/env.list
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  digibank-transactions-svc:
    image: boeboe/digibank-transactions-svc
    env_file:
      - ./microservices/transactions/env.list
    ports:
      - "3600:3600"
    depends_on:
      - mongo

  digibank-userbase-svc:
    image: boeboe/digibank-userbase-svc
    env_file:
      - ./microservices/userbase/env.list
    ports:
      - "4200:4200"
    depends_on:
      - mongo
      - digibank-accounts-svc
      - digibank-authentication-svc
      - digibank-bills-svc
      - digibank-transactions-svc
