---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: digibank-portal
  labels:
    account: portal

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: portal
  labels:
    chart: 'digibank-{{ .Chart.Version | replace "+" "_" }}'
    app: portal
    version: "{{ .Values.portal.version }}"
spec:
  replicas: {{ .Values.portal.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: portal
        version: "{{ .Values.portal.version }}"
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: digibank-portal
      containers:
        - name: portal
          image: "{{ .Values.portal.image }}:{{ .Values.portal.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: portal-port
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: "{{ .Values.livenessProbe.endpointPath}}"
              port: {{ .Values.portal.servicePort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds}}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds}}
          readinessProbe:
            httpGet:
              path: "{{ .Values.readinessProbe.endpointPath}}"
              port: {{ .Values.portal.servicePort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds}}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds}}
          resources:
            requests:
              cpu: "{{ .Values.image.resources.requests.cpu }}"
              memory: "{{ .Values.image.resources.requests.memory }}"
          env:
            ##### Environment variables #####
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: mongoUrl
            - name: CURRENCY
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: currency
            - name: SESSION_SECRET
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: sessionSecret
            ##### Accounts #####      
            - name: CREATE_ACCOUNT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: createAccountEndpoint
            - name: GET_ACCOUNTS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: getAccountsEndpoint
            - name: ACCOUNT_WITHDRAW_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: accountWithdrawEndpoint
            - name: ACCOUNT_DEPOSIT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: accountDepositEndpoint
            - name: DROP_ACCOUNTS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: dropAccountsEndpoint
            ##### Authentication #####
            - name: SIGNUP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: signupEndpoint
            - name: LOGIN_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: loginEndpoint
            - name: GET_USERS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: getUsersEndpoint
            ##### Bills #####
            - name: GET_BILLS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: getBillsEndpoint
            - name: UPSERT_BILL_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: upsertBillEndpoint
            - name: DROP_BILLS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: dropBillsEndpoint
            ##### Support #####
            - name: CHAT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: chatEndpoint
            ##### Transactions #####
            - name: CREATE_TRANSACTION_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: createTransactionEndpoint
            - name: GET_TRANSACTIONS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: getTransactionsEndpoint                
            - name: DROP_TRANSACTIONS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: dropTransactionsEndpoint

---
{{ if .Values.portal.serviceNodePortEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: portal-nodeport
  labels:
    chart: 'digibank-{{ .Chart.Version | replace "+" "_" }}'
    app: portal
    version: "{{ .Values.portal.version }}"
spec:
  ports:
    - name: "{{ .Values.portal.servicePortName }}"
      port: {{ .Values.portal.servicePort }}
      nodePort: {{ .Values.portal.serviceNodePort }}
      targetPort: portal-port
  selector:
    app: portal
  type: NodePort
{{ else }}
apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    chart: 'digibank-{{ .Chart.Version | replace "+" "_" }}'
    app: portal
    version: "{{ .Values.portal.version }}"
spec:
  ports:
    - name: "{{ .Values.portal.servicePortName }}"
      port: {{ .Values.portal.servicePort }}
      targetPort: portal-port
  selector:
    app: portal
{{ end }}

---
{{ if .Values.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: portal-hpa-policy
  labels:
    app: portal
    chart: 'digibank-{{ .Chart.Version | replace "+" "_" }}'
    version: "{{ .Values.portal.version }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: portal
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPUUtilizationPercentage }}
{{ end }}

---
apiVersion: policy.aspenmesh.io/v1alpha1
kind: Application
metadata:
  name: digibank
spec:
  inbound:
    ports:
      - number: 3000
        protocol: HTTP
        paths:
          - expose:
              public: true
              jwtSecured: false
            uri:
              prefix: "/"

---
apiVersion: policy.aspenmesh.io/v1alpha1
kind: SecureIngress
metadata:
  name: digibank
  annotations:
    external-dns.alpha.kubernetes.io/target: 10.1.1.5
spec:
  domainName: "digibank.f5demo.org"
  jwt:
    - issuer: "admin@digibank.f5demo.org"
      jwksUri: "https://10.1.1.4:4444/.well-known/jwks.json"
  exposedApplications:
    - applicationReference:
        name: digibank
        namespace: digibank
      serviceReference:
        name: portal
        namespace: digibank
