---
apiVersion: v1
kind: ConfigMap
metadata:
  name: digibank-configmap
data:
  ##### Environment variables #####
  mongoUrl: "mongodb://mongo:27017/digibank"
  currency: "EUR"
  sessionSecret: "w3hMHPfe4jK21UHYY0Ph"

  ##### Accounts #####
  createAccountEndpoint: "/api/accounts/create"
  getAccountsEndpoint: "/api/accounts/get"
  accountWithdrawEndpoint: "/api/accounts/withdraw"
  accountDepositEndpoint: "/api/accounts/deposit"
  dropAccountsEndpoint: "/api/accounts/drop"

  ##### Authentication #####
  signupEndpoint: "/api/user/create"
  loginEndpoint: "/api/user/authenticate"
  getUsersEndpoint: "/api/user/get"

  ##### Bills #####
  getBillsEndpoint: "/api/bills/get"
  upsertBillEndpoint: "/api/bills/create"
  dropBillsEndpoint: "/api/bills/drop"

  ##### Support #####
  chatEndpoint: "/api/messages/create"

  ##### Transactions #####
  createTransactionEndpoint: "/api/transactions/create"
  getTransactionsEndpoint: "/api/transactions/get"
  dropTransactionsEndpoint: "/api/transactions/drop"
