---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
    version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        version: latest
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: digibank-mongo
      containers:
        - name: mongo
          image: mvertes/alpine-mongo
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongo-port
              containerPort: 27017
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 5
            timeoutSeconds: 1
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    app: accounts
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: accounts
        version: 1.0.0
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: digibank-accounts
      containers:
        - name: accounts
          image: boeboe/digibank-accounts-svc:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: accounts-port
              containerPort: 3400
          livenessProbe:
            httpGet:
              path: "/health"
              port: 3400
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: "/health"
              port: 3400
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: mongoUrl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  labels:
    app: authentication
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: authentication
        version: 1.0.0
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: digibank-authentication
      containers:
        - name: authentication
          image: boeboe/digibank-authentication-svc:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: auth-port
              containerPort: 3200
          livenessProbe:
            httpGet:
              path: "/health"
              port: 3200
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: "/health"
              port: 3200
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: mongoUrl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bills
  labels:
    app: bills
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bills
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: bills
        version: 1.0.0
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: digibank-bills
      containers:
        - name: bills
          image: boeboe/digibank-bills-svc:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: bills-port
              containerPort: 3800
          livenessProbe:
            httpGet:
              path: "/health"
              port: 3800
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: "/health"
              port: 3800
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: mongoUrl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  labels:
    app: portal
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: portal
        version: 1.0.0
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: digibank-portal
      containers:
        - name: portal
          image: boeboe/digibank-portal-svc:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: portal-port
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: "/health"
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: "/health"
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
          env:
            ##### Environment variables #####
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: mongoUrl
            - name: CURRENCY
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: currency
            - name: SESSION_SECRET
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: sessionSecret
            ##### Accounts #####      
            - name: CREATE_ACCOUNT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: createAccountEndpoint
            - name: GET_ACCOUNTS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: getAccountsEndpoint
            - name: ACCOUNT_WITHDRAW_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: accountWithdrawEndpoint
            - name: ACCOUNT_DEPOSIT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: accountDepositEndpoint
            - name: DROP_ACCOUNTS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: dropAccountsEndpoint
            ##### Authentication #####
            - name: SIGNUP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: signupEndpoint
            - name: LOGIN_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: loginEndpoint
            - name: GET_USERS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: getUsersEndpoint
            ##### Bills #####
            - name: GET_BILLS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: getBillsEndpoint
            - name: UPSERT_BILL_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: upsertBillEndpoint
            - name: DROP_BILLS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: dropBillsEndpoint
            ##### Support #####
            - name: CHAT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: chatEndpoint
            ##### Transactions #####
            - name: CREATE_TRANSACTION_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: createTransactionEndpoint
            - name: GET_TRANSACTIONS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: getTransactionsEndpoint                
            - name: DROP_TRANSACTIONS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: dropTransactionsEndpoint
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: support
  labels:
    app: support
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: support
        version: 1.0.0
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: digibank-support
      containers:
        - name: support
          image: boeboe/digibank-support-svc:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: support-port
              containerPort: 4000
          livenessProbe:
            httpGet:
              path: "/health"
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: "/health"
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: mongoUrl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions
  labels:
    app: transactions
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: transactions
        version: 1.0.0
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: digibank-transactions
      containers:
        - name: transactions
          image: boeboe/digibank-transactions-svc:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: trans-port
              containerPort: 3600
          livenessProbe:
            httpGet:
              path: "/health"
              port: 3600
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: "/health"
              port: 3600
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: mongoUrl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userbase
  labels:
    app: userbase
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userbase
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: userbase
        version: 1.0.0
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: digibank-userbase
      containers:
        - name: userbase
          image: "boeboe/digibank-userbase-svc:1.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: userbase-port
              containerPort: 4200
          livenessProbe:
            httpGet:
              path: "/health"
              port: 4200
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: "/health"
              port: 4200
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
          env:
            ##### Environment variables #####
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: mongoUrl
            - name: CURRENCY
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: currency
            ##### Accounts #####
            - name: DROP_ACCOUNTS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: dropAccountsEndpoint
            ##### Authentication #####
            - name: GET_USERS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: getUsersEndpoint
            ##### Bills #####
            - name: UPSERT_BILL_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: upsertBillEndpoint
            - name: DROP_BILLS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: dropBillsEndpoint
            ##### Transactions #####
            - name: CREATE_TRANSACTION_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: createTransactionEndpoint
            - name: DROP_TRANSACTIONS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digibank-configmap
                  key: dropTransactionsEndpoint
