---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: account-hpa-policy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: accounts
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: authentication-hpa-policy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authentication
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bills-hpa-policy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bills
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: portal-hpa-policy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: portal
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: support-hpa-policy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: support
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: transactions-hpa-policy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transactions
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
---
