---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: digibank-mongo
  labels:
    account: mongo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: digibank-accounts
  labels:
    account: accounts
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: digibank-authentication
  labels:
    account: authentication
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: digibank-bills
  labels:
    account: bills
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: digibank-portal
  labels:
    account: portal
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: digibank-support
  labels:
    account: support
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: digibank-transactions
  labels:
    account: transactions
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: digibank-userbase
  labels:
    account: userbase
