
---
##### General config #####
revisionHistoryLimit: 3

config:
  currency: "EUR"
  mongoUrl: "mongodb://mongo:27017/digibank"
  sessionSecret: "w3hMHPfe4jK21UHYY0Ph"

image:
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 300m
      memory: 512Mi

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  endpointPath: "/health"

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  endpointPath: "/health"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

##### Micro-service specific config #####

mongo:
  enabled: true
  version: latest
  image: "mvertes/alpine-mongo"
  servicePort: 27017
  servicePortName: tcp-mongo
  pvSize: 2Gi
  pvAccessMode: "ReadWriteOnce"

accounts:
  version: 1.0.0
  image: "boeboe/digibank-accounts-svc"
  replicaCount: 1
  servicePort: 3400
  servicePortName: http-accounts

authentication:
  version: 1.0.0
  image: "boeboe/digibank-authentication-svc"
  replicaCount: 1
  servicePort: 3200
  servicePortName: http-auth

bills:
  version: 1.0.0
  image: "boeboe/digibank-bills-svc"
  replicaCount: 1
  servicePort: 3800
  servicePortName: http-bills

portal:
  version: 1.0.0
  image: "boeboe/digibank-portal-svc"
  replicaCount: 1
  servicePort: 3000
  servicePortName: http-portal
  serviceNodePortEnabled: false
  serviceNodePort: 30300

support:
  version: 1.0.0
  image: "boeboe/digibank-support-svc"
  replicaCount: 1
  servicePort: 4000
  servicePortName: http-support

transactions:
  version: 1.0.0
  image: "boeboe/digibank-transactions-svc"
  replicaCount: 1
  servicePort: 3600
  servicePortName: http-trans

userbase:
  version: 1.0.0
  image: "boeboe/digibank-userbase-svc"
  replicaCount: 1
  servicePort: 4200
  servicePortName: http-userbase
